### PR TITLE
Docker upgrades

### PR DESCRIPTION
**Pull request by alexiswl**
## Issues Fixed

* Installs bedtools for #449 
* Installs samtools for #457
* Installs R 4.0 and StructuralVariantAnnotation bumped from 1.2.0 to 1.6.0 for #457 
* Added instructions and dockerfile for creating 'target' folder for release #458

### Dockerfile Upgrade:  (6ad0bd22515b477c2cfd00657f10aa5d039f46cf)
* Upgraded ubuntu from bionic (18) to focal (20)  
* Removed aarnet soures, causing issues in R4.0 upgrade  
* Used instructions on https://linuxize.com/post/how-to-install-r-on-ubuntu-20-04/ for installing R 4.0  
* Re-structured apt-installations in list format  
* Install Biobase as it's a dependency of NMF.
* Install NMF after everything else

### Building Gridss Update (d49bec7d2693232b5e9e0b382bcfa73abf443a89)
* Created dockerfile for building a container / environment for creating the target directory.  
* Added Readme to building said container.

### CODE REVIEW

**Comment by d-cameron** [comment]
> Created dockerfile for building a container / environment for creating the target directory.

I'm in the process of refactoring the docker container to use the github release artifacts (now that gridsstools source is included as a release artifact). This seems like a more robust approach than relying on the local environment.

**Comment by d-cameron** [comment]
Is there a way to rebase a pull request to a different branch? I make all GRIDSS changes are on dev branch so the master matches the latest released version.

**Comment by alexiswl** [comment]
> Is there a way to rebase a pull request to a different branch? I make all GRIDSS changes on the dev branch so the master matches the latest released version.

Yup can do, and will make sure pull-requests in future are sent to the dev branch

**Comment by alexiswl** [comment]
Superceded by #461

**Pull request closed without merging**
